apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-code-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /usr/src
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-code-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi