apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /k3d/images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi