[package]
name = "runtime"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
# lto = true
# opt-level = 'z'
debug = true

[dependencies]
html = {path = "../html"}
crabquery = "0.1.7"
html5ever = "0.25.1"
markup5ever_arcdom = "0.1.1"
tendril = "0.4.1"
scraper = "0.12.0"
ego-tree = "0.6.2"
