[package]
name = "testlib"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.51", features = ["full", "parsing", "extra-traits"] }
quote = "1.0.7"