[package]
name = "MySharedLibRust"
version = "0.1.0"
authors = ["Daniel Leite <1985.daniel@gmail.com>"]
edition = "2018"

[lib]
name = "MySharedLib"
crate_type = ["dylib"]

[dependencies]
serde = { versuin = "1.0.117",features = ["derive"] }
serde_json = "1.0.59"
