[package]
name = "columnar-db"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
libc = "0.2"
errno = "0.2.7"
rand = "0.7.3"
crossbeam-channel = "0.5"
testlib = {path = "../testlib"}