[package]
name = "utils"
version = "0.1.0"
authors = ["Daniel Leite <xunilrj@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extension-trait = "1.0.0"