[package]
name = "sstable"
version = "0.1.0"
authors = ["Daniel Leite <1985.daniel@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "*"
byteorder = "*"
pretty_env_logger = "0.4.0"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"

[dependencies.log]
version = "0.4"
features = ["max_level_trace", "release_max_level_info"]