[package]
name = "app"
version = "0.1.0"
authors = ["Daniel Leite <xunilrj@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
runtime = { path = "../runtime" }
html = { path = "../html" }