[package]
name = "columnar-db"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[lib]
name = "hallo"
path = "src/lib.rs"

[dependencies]
nix = "0.19.0"
crossbeam-channel = "0.5"
testlib = {path = "../testlib"}