[package]
name = "helloworld"
version = "0.1.0"
authors = ["Daniel Frederico Lins Leite <xunilrj@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.54"
js-sys = "0.3.31"